#!/bin/bash
# harness-init.sh - Initialize Spec Kit Parallel Orchestrator Harness
# Usage: ./harness-init.sh [project-name]

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/harness-lib.sh"

# Project name (optional, defaults to directory name)
PROJECT_NAME="${1:-$(basename "$PWD")}"
HARNESS_DIR="${HARNESS_DIR:-specs/harness}"

log_info "Initializing Spec Kit Parallel Orchestrator Harness..."
log_info "Project: $PROJECT_NAME"

# Check requirements
if ! check_requirements; then
    exit 1
fi

# Check if already initialized
if harness_exists; then
    log_warning "Harness already exists at $HARNESS_DIR"
    read -p "Reinitialize? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Aborted."
        exit 0
    fi
    # Backup existing
    backup_dir="${HARNESS_DIR}.backup.$(date +%Y%m%d%H%M%S)"
    log_info "Backing up existing harness to $backup_dir"
    mv "$HARNESS_DIR" "$backup_dir"
fi

# Create harness directory
mkdir -p "$HARNESS_DIR"
log_success "Created directory: $HARNESS_DIR"

# Create feature_list.json
TIMESTAMP=$(get_timestamp)
cat > "$HARNESS_DIR/feature_list.json" << EOF
{
  "project": "$PROJECT_NAME",
  "created": "$TIMESTAMP",
  "updated": "$TIMESTAMP",
  "features": [
    {
      "id": "F001",
      "category": "functional",
      "priority": "P1",
      "description": "Sample feature - replace with your actual features",
      "steps": [
        "Step 1: Describe the first step",
        "Step 2: Describe the second step",
        "Step 3: Describe the third step"
      ],
      "status": "pending",
      "depends_on": [],
      "blocked_reason": null,
      "started_at": null,
      "completed_at": null,
      "commits": []
    }
  ]
}
EOF
log_success "Created: $HARNESS_DIR/feature_list.json"

# Create progress.log.md
cat > "$HARNESS_DIR/progress.log.md" << EOF
# Progress Log: $PROJECT_NAME

> Auto-generated by Spec Kit Parallel Orchestrator Harness
> Created: $(get_display_date)

## How to Use

1. Edit \`feature_list.json\` to define your features
2. Run \`harness-start.sh\` to begin a session
3. Implement the feature
4. Run \`harness-end.sh\` to verify and complete

---

EOF
log_success "Created: $HARNESS_DIR/progress.log.md"

# Create session_state.json
cat > "$HARNESS_DIR/session_state.json" << EOF
{
  "session_id": 0,
  "tool": "",
  "started_at": null,
  "current_feature": null,
  "start_commit": null,
  "end_commit": null,
  "e2e_result": null,
  "status": "idle"
}
EOF
log_success "Created: $HARNESS_DIR/session_state.json"

# Create init.sh template
cat > "$HARNESS_DIR/init.sh" << 'EOF'
#!/bin/bash
# init.sh - Environment check script
# Customize this script to verify your project's dependencies

set -euo pipefail

echo "=== Environment Check ==="

# Check Node.js
if command -v node &> /dev/null; then
    NODE_VERSION=$(node --version)
    echo "✓ Node.js: $NODE_VERSION"
else
    echo "✗ Node.js not found"
    exit 1
fi

# Check npm
if command -v npm &> /dev/null; then
    NPM_VERSION=$(npm --version)
    echo "✓ npm: $NPM_VERSION"
else
    echo "✗ npm not found"
    exit 1
fi

# Check if node_modules exists
if [ -d "node_modules" ]; then
    echo "✓ node_modules exists"
else
    echo "⚠ node_modules not found. Run 'npm install' first."
fi

# Add your custom checks here:
# - Database connection
# - Environment variables
# - Required services
# - Configuration files

echo "=== Environment OK ==="
EOF
chmod +x "$HARNESS_DIR/init.sh"
log_success "Created: $HARNESS_DIR/init.sh"

# Create .harness-config.json for custom settings
cat > "$HARNESS_DIR/.harness-config.json" << EOF
{
  "e2e_command": "npm test",
  "e2e_timeout": 300,
  "require_clean_tree": true,
  "auto_commit": false,
  "parallel_tasks": {
    "min": 3,
    "max": 6
  }
}
EOF
log_success "Created: $HARNESS_DIR/.harness-config.json"

# Summary
echo ""
log_success "=== Harness Initialized ==="
echo ""
echo "Next steps:"
echo "  1. Edit $HARNESS_DIR/feature_list.json to define your features"
echo "  2. Customize $HARNESS_DIR/init.sh for your project"
echo "  3. Configure E2E command in $HARNESS_DIR/.harness-config.json"
echo "  4. Run harness-start.sh to begin your first session"
echo ""
echo "Harness files:"
ls -la "$HARNESS_DIR"
